version: '3.7'
services:
  cbr-converter-ui:
    build:
      dockerfile: Dockerfile.compose
      context: .
    ports:
    - 80:80
    networks:
      - cbr-network-frontend


networks:
  cbr-network-frontend:
    external:
      name: cbr-network